import random
from loguru import logger
from app.services.activity_suggestion.state import RecommendationState
from app.ai.structured_outputs.activity_suggestion.select_activities import Activity

def process_slot_diversity(slot_activities: list, slot_name: str, mapping_dict: dict, category_counts: dict, user_id: str) -> list:
    kept_activities = []
    for act in slot_activities:
        mapped_item = mapping_dict.get(act.id)
        if not mapped_item:
            cat = act.activity_type
            daily_time = ""
        else:
            cat = mapped_item.get("parent_category_name") or act.activity_type
            daily_time = str(mapped_item.get("daily_time", "")).lower()
            
        # 1a. Slot validation
        if daily_time and daily_time != 'none' and daily_time != 'any':
            if slot_name not in daily_time:
                logger.info(f"Slot rule triggered: Removed activity '{act.name}' from {slot_name} because its daily_time is '{daily_time}'")
                continue

        # 1b. Well-being Checks constraint
        if cat == 'Well-being Checks' and 'Well-being Checks' in category_counts:
            logger.warning(f"Cannot add well being checks more than once in the routine.")
            continue
            
        # 1c. General Diversity
        count = category_counts.get(cat, 0)
        if count < 2:
            category_counts[cat] = count + 1
            kept_activities.append(act)
        else:
            logger.info(f"Diversity rule triggered: Removed activity '{act.name}' (Category: {cat}) for User {user_id}")
    return kept_activities

def fill_slot(slot_activities: list, slot_name: str, library: list, scheduled_ids: set, category_counts: dict, user_id: str) -> list:
    while len(slot_activities) < 3:
        available = []
        for item in library:
            temp_id = item.get("id")
            cat = item.get("category")
            daily_time = str(item.get("slot", "")).lower()
            
            if temp_id in scheduled_ids:
                continue
                
            # Slot validation
            if daily_time and daily_time != 'none' and daily_time != 'any':
                if slot_name not in daily_time:
                    continue

            # Well-being Checks constraint
            if cat == 'Well-being Checks' and 'Well-being Checks' in category_counts:
                continue

            if category_counts.get(cat, 0) < 2:
                available.append(item)
        
        if not available:
            logger.warning(f"Could not fill slot '{slot_name}' for User {user_id}: No eligible activities left in library.")
            break
            
        chosen = random.choice(available)
        temp_id = chosen.get("id")
        cat = chosen.get("category")
        if cat == 'Well-being Checks' and cat in category_counts:
            logger.warning(f"Cannot add well being checks more than once in the routine.")
            continue

        new_act = Activity(
            id=temp_id,
            name=chosen.get("name"),
            activity_type=cat,
            time=chosen.get("duration_mins", 10),
            benefits=["Mental Wellness"]
        )
        
        slot_activities.append(new_act)
        scheduled_ids.add(temp_id)
        category_counts[cat] = category_counts.get(cat, 0) + 1
        
        logger.info(f"Minimum rule triggered: Added random activity '{new_act.name}' to {slot_name} for User {user_id}")
        
    return slot_activities

async def verify_routine(state: RecommendationState) -> dict:
    """
    Validates and adjusts the activity routine generated by the LLM.
    Enforces:
    1. Diversity: No more than 2 activities from the same parent category across the entire routine.
    2. Minimums: At least 3 activities per slot (morning, afternoon, evening).
    """
    user_id = state.get("user_id")
    logger.info(f"NODE START: verify_routine | User: {user_id}")

    routine = state.get("activity_routine")
    if not routine:
        logger.warning(f"No activity routine found in state for User {user_id}")
        return {}

    library = state.get("activity_library", [])
    mapping_dict = state.get("mapping_dict", {})
    
    # 1. Enforce Diversity & Slot Validity
    category_counts = {}

    routine.morning = process_slot_diversity(routine.morning, "morning", mapping_dict, category_counts, user_id)
    routine.afternoon = process_slot_diversity(routine.afternoon, "afternoon", mapping_dict, category_counts, user_id)
    routine.evening = process_slot_diversity(routine.evening, "evening", mapping_dict, category_counts, user_id)

    # 2. Enforce Minimums (3 per slot)
    scheduled_ids = set()
    for slot in [routine.morning, routine.afternoon, routine.evening]:
        for act in slot:
            scheduled_ids.add(act.id)

    routine.morning = fill_slot(routine.morning, "morning", library, scheduled_ids, category_counts, user_id)
    routine.afternoon = fill_slot(routine.afternoon, "afternoon", library, scheduled_ids, category_counts, user_id)
    routine.evening = fill_slot(routine.evening, "evening", library, scheduled_ids, category_counts, user_id)

    logger.info(f"NODE FINISHED: verify_routine | User: {user_id}")
    return {"activity_routine": routine}
