name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}  # Your VPS IP address or domain
        username: ${{ secrets.SSH_USERNAME }}  # SSH username for the VPS
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key stored in secrets
        port: 22  # SSH port, usually 22
        script: |
          cd /home/ubuntu/mindalcove-python-backend
          git pull origin dev  # Pull the latest code from the repository
          cd /home/ubuntu/mindalcove-python-backend
          docker compose down
          docker compose up -d --build
